parameters:
#    form_wizard.example.class: CMS\FormWizardBundle\Example

services:
#    form_wizard.example:
#        class: %form_wizard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
