parameters:
    form_wizard.twig.class: CMS\FormWizardBundle\Twig\FormWizardExtension

services:
    cms.form_wizard.twig:
        class: %form_wizard.twig.class%
        arguments: [@service_container]
        tags:
          - { name: twig.extension}
